Yaml modified

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -119,12 +119,16 @@ jobs:
 
             if [ -z "$test_files" ]; then
               echo "No test files imported"
-              exit 0
+              continue
             else
               # 3. Print the collected test files
               echo "Test files that import addcmul_model:"
               echo "$test_files"
               # 4. Run pytest only on the collected files
-              pytest $test_files || exit 1  # Fail only if pytest fails
+              pytest $test_files
+              if [ $? -ne 0 ]; then
+                echo "Tests failed for $item"
+                exit 1
+              fi
             fi
           done
