MOdify yaml file

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -119,11 +119,12 @@ jobs:
 
             if [ -z "$test_files" ]; then
               echo "No test files imported"
+              exit 0
             else
               # 3. Print the collected test files
               echo "Test files that import addcmul_model:"
               echo "$test_files"
               # 4. Run pytest only on the collected files
-              pytest $test_files
+              pytest $test_files || exit 1  # Fail only if pytest fails
             fi
           done
